root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["assets", "tmp", "vendor"]

[misc]
clean_on_exit = true

# Add logging for build events
[build.log]
time = true
level = "debug"

# Add more detailed logging
[log]
main_only = false
time = true

[screen]
clear_on_rebuild = true
keep_scroll = false

# Force build on start
[build.start]
force_build = true